# Generated by Django 5.2.7 on 2025-10-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vacas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arete', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=100)),
                ('etapa', models.CharField(choices=[('ternero', 'ternero'), ('novillo', 'novillo'), ('joven', 'joven'), ('adulta', 'adulta'), ('vieja', 'vieja')], max_length=50)),
                ('lote', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=6)),
                ('madre', models.CharField(max_length=100)),
                ('padre', models.CharField(max_length=100)),
            ],
        ),
    ]
