# Generated by Django 5.2.7 on 2025-11-12 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Lote')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad Máxima')),
                ('estado', models.BooleanField(default=True, verbose_name='Lote Activo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoDesleche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desleche', models.DateField(verbose_name='Fecha de Desleche (Destete)')),
                ('numero_animales', models.IntegerField(verbose_name='Número de Animales Deslechados')),
                ('peso_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso Promedio (kg)')),
                ('observaciones', models.TextField(blank=True)),
                ('lote_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desleches_recibidos', to='twocows.lote', verbose_name='Lote de Destino')),
                ('lote_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desleches_realizados', to='twocows.lote', verbose_name='Lote de Origen')),
            ],
        ),
        migrations.CreateModel(
            name='vacas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arete', models.CharField(max_length=50, unique=True, verbose_name='Número de Arete')),
                ('raza', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=6)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales_en_lote', to='twocows.lote', verbose_name='Lote Actual')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='twocows.vacas', verbose_name='Arete de la Madre')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias', to='twocows.vacas', verbose_name='Arete del Padre')),
            ],
        ),
        migrations.CreateModel(
            name='EventoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACUNA', 'Vacunación'), ('TRATAMIENTO', 'Tratamiento'), ('DESPARASITACION', 'Desparasitación')], max_length=50, verbose_name='Tipo de Evento(Vacuna, tratamiento, Desparasitación)')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('producto_usado', models.CharField(max_length=150, verbose_name='Producto/Medicina Usada')),
                ('dosis', models.CharField(blank=True, max_length=50, verbose_name='Dosis Aplicada')),
                ('observaciones', models.TextField(blank=True)),
                ('lote_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_grupales', to='twocows.lote', verbose_name='Lote Afectado')),
                ('vaca_afectada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_individuales', to='twocows.vacas', verbose_name='Animal Afectado')),
            ],
        ),
    ]
