# Generated by Django 5.2.7 on 2025-11-26 05:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Lote')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área hectareas')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad Máxima')),
                ('estado', models.BooleanField(default=True, verbose_name='Lote Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Raza')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICINA', 'Medicina'), ('VACUNA', 'Vacuna')], max_length=50)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Disponible')),
                ('unidad', models.CharField(max_length=20, verbose_name='Unidad de Medida (kg, litros, dosis, etc.)')),
                ('fecha_venc', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_pasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Pasto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Pasto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Jefe de Campo'), ('CUIDADOR', 'Cuidador de Vacas'), ('ORDENADOR', 'Ordeñador'), ('POTRERO', 'Encargado de Potrero')], default='CUIDADOR', max_length=20, verbose_name='Rol del Usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EventoDesleche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desleche', models.DateField(verbose_name='Fecha de Desleche (Destete)')),
                ('numero_animales', models.IntegerField(verbose_name='Número de Animales Deslechados')),
                ('peso_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso Promedio (kg)')),
                ('observaciones', models.TextField(blank=True)),
                ('lote_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_desleche_destino', to='twocows.lote', verbose_name='Lote de Destino')),
                ('lote_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_desleche_origen', to='twocows.lote', verbose_name='Lote de Origen')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='pasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twocows.tipo_pasto', verbose_name='Tipo de Pasto'),
        ),
        migrations.CreateModel(
            name='Vaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arete', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'El número de arete solo debe contener números.')], verbose_name='Número de Arete')),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=6)),
                ('peso_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso inicial (kg)')),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso Actual (kg)')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo en hato'), ('VENDIDO', 'Vendido'), ('MUERTO', 'Fallecido'), ('PERDIDO', 'Perdido/Robado')], default='ACTIVO', max_length=20)),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacas_en_lote', to='twocows.lote', verbose_name='Lote Actual')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='twocows.vaca', verbose_name='Arete de la Madre')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias', to='twocows.vaca', verbose_name='Arete del Padre')),
                ('raza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twocows.raza', verbose_name='Raza')),
            ],
            options={
                'verbose_name': 'Vaca/Animal',
                'verbose_name_plural': 'Inventario de Animales',
            },
        ),
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (kg)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_peso', to='twocows.vaca', verbose_name='Vaca')),
            ],
        ),
        migrations.CreateModel(
            name='EventoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACUNA', 'Vacunación'), ('TRATAMIENTO', 'Tratamiento'), ('DESPARASITACION', 'Desparasitación'), ('ENFERMEDAD', 'Enfermedad')], max_length=50, verbose_name='Tipo de Evento')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('dosis', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de dosis aplicada', max_digits=8, null=True, verbose_name='Dosis Aplicada')),
                ('peso_animal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso del Animal (kg)')),
                ('observaciones', models.TextField(blank=True)),
                ('lote_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sanitarios', to='twocows.lote', verbose_name='Lote Afectado')),
                ('producto_usado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='twocows.recursos', verbose_name='Medicina Usada')),
                ('vaca_afectada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sanitarios', to='twocows.vaca', verbose_name='Animal Afectado')),
            ],
        ),
    ]
