# Generated by Django 5.2.7 on 2025-11-13 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twocows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacas',
            name='arete',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'El número de arete solo debe contener números.')], verbose_name='Número de Arete'),
        ),
    ]
