# Generated by Django 5.2.6 on 2025-11-26 17:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twocows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventosanitario',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='eventosanitario',
            name='producto_usado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tempo_password',
            field=models.BooleanField(default=True, verbose_name='Debe de cambiarse la contraseña'),
        ),
        migrations.CreateModel(
            name='DetalleEventoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad/Dosis Usada')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_usados', to='twocows.eventosanitario', verbose_name='Evento Sanitario')),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='twocows.recursos', verbose_name='Recurso Usado')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionLeche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Ordeño')),
                ('cantidad_leche', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad de Leche (litros)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('jornada', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10, verbose_name='Jornada de Ordeño')),
                ('ordeñador', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ORDENADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produccion_leche', to='twocows.vaca', verbose_name='Vaca Ordeñada')),
            ],
            options={
                'verbose_name': 'Registro de Leche',
                'verbose_name_plural': 'Producción de Leche',
                'ordering': ['-fecha', 'vaca'],
            },
        ),
    ]
