# Generated by Django 5.2.7 on 2025-11-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twocows', '0002_alter_vacas_arete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Raza')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.AlterField(
            model_name='vacas',
            name='raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twocows.raza', verbose_name='Raza'),
        ),
    ]
